// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARfDcEvMSuZjvs2UtB1sQvlSBuF7UH8vk',
    appId: '1:396044148836:web:8fdb9b9591d1af2b9dff71',
    messagingSenderId: '396044148836',
    projectId: 'course-flutter-motobike',
    authDomain: 'course-flutter-motobike.firebaseapp.com',
    storageBucket: 'course-flutter-motobike.appspot.com',
    measurementId: 'G-HT5B0LRQX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC8E3X8AnMVOHhpthad-1WKX6liHD4RLo',
    appId: '1:396044148836:android:35930a891115732c9dff71',
    messagingSenderId: '396044148836',
    projectId: 'course-flutter-motobike',
    storageBucket: 'course-flutter-motobike.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgRmaM11NrRELu4X_RIq9ZtjBhWRQ85hw',
    appId: '1:396044148836:ios:65c6dc3958208ecc9dff71',
    messagingSenderId: '396044148836',
    projectId: 'course-flutter-motobike',
    storageBucket: 'course-flutter-motobike.appspot.com',
    iosBundleId: 'com.example.motobike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgRmaM11NrRELu4X_RIq9ZtjBhWRQ85hw',
    appId: '1:396044148836:ios:65c6dc3958208ecc9dff71',
    messagingSenderId: '396044148836',
    projectId: 'course-flutter-motobike',
    storageBucket: 'course-flutter-motobike.appspot.com',
    iosBundleId: 'com.example.motobike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARfDcEvMSuZjvs2UtB1sQvlSBuF7UH8vk',
    appId: '1:396044148836:web:ffc177fedb17969c9dff71',
    messagingSenderId: '396044148836',
    projectId: 'course-flutter-motobike',
    authDomain: 'course-flutter-motobike.firebaseapp.com',
    storageBucket: 'course-flutter-motobike.appspot.com',
    measurementId: 'G-27J5TG44SN',
  );
}
